[package]
name = "peer-share"
version = "0.1.0"
authors = ["Nick Stebb <n.stebbings@gmail.com>"]
edition = "2018"

[lib]
name = "peershare"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.0.107"
serde = "1"
holo_hash = "0.0.7"
jsonschema-valid = "0.4.0"
serde_json = "1.0.64"
